SELECT
  GOURMET.FAMILIA.NOMBREFAMILIA,
  GOURMET.CLIENTE.REGION,
  GOURMET.CLIENTE.PROFESION,
  GOURMET.CLIENTE.NUMEROHIJOS,
  GOURMET.CLIENTE.SEXO
FROM GOURMET.LINEASTICKET
  JOIN GOURMET.PRODUCTO ON GOURMET.LINEASTICKET.CODPRODUCTO = GOURMET.PRODUCTO.CODPRODUCTO
  JOIN GOURMET.CABECERATICKET ON GOURMET.LINEASTICKET.CODVENTA = GOURMET.CABECERATICKET.CODVENTA
  JOIN GOURMET.CLIENTE ON GOURMET.CABECERATICKET.CODCLIENTE = GOURMET.CLIENTE.CODCLIENTE
  JOIN GOURMET.NOMBRESUBFAMILIA ON GOURMET.PRODUCTO.NOMBRESUBFAMILIA = GOURMET.NOMBRESUBFAMILIA.NOMBRESUBFAMILIA
  JOIN GOURMET.FAMILIA ON GOURMET.NOMBRESUBFAMILIA.NOMBREFAMILIA = GOURMET.FAMILIA.NOMBREFAMILIA
ORDER BY GOURMET.PRODUCTO.DESCRIPCION;
